openapi: 3.0.4
info:
  title: URL Title
  description: URL Title is a simple tool for getting the title of a web page. It returns the title of the web page based on the URL provided.
  termsOfService: https://apiverve.com/terms/
  contact:
    name: APIVerve Support
    email: hello@apiverve.com
    url: https://apiverve.com/contact
  version: 1.0.9
externalDocs:
  description: Learn more about APIVerve
  url: https://docs.apiverve.com?utm_source=openapi
servers:
- url: https://api.apiverve.com/
paths:
  /v1/urltitle:
    post:
      summary: Get Title of Web Page
      description: URL Title is a simple tool for getting the title of a web page. It returns the title of the web page based on the URL provided.
      operationId: urltitle
      parameters: []
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: status
                  error:
                    type: string
                    description: error
                  data:
                    type: string
                    description: data
              example:
                status: ok
                error: 
                data:
                  title: Google Joins $250 Million Deal to Support Newsrooms in California - The New York Times
                  h1:
                  - Google Joins $250 Million Deal to Support Newsrooms in California
        '401':
          description: Your request was not authorized, or your API Key was invalid
        '404':
          description: Requested resource was not found
        '500':
          description: A server error has occured, try again later
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                url:
                  type: string
                  description: The URL of the web page to get the title of
                  example: https://blog.apiverve.com/chuck-norris-api-how-to
              required:
              - url
              example:
                url: https://blog.apiverve.com/chuck-norris-api-how-to
components:
  securitySchemes:
    api_key:
      type: apiKey
      name: x-api-key
      in: header
security:
- api_key: []
